- package.json
- src/cli.js
- src/parser.js
Introduce a new `-s --stdin` flag to make it clear/intentional ?
Example:
`cat test/data/test.scss | bin/sassdoc -vs`
> Add ability to pipe SassDoc into `stdin`

- src/sassdoc.js
- src/utils.js
* When it's a string, we use it as parent, stripping eventual glob
patterns.
* When it's an array, or we don't have any `src` because of streaming,
we don't check anything.
---
* Related: SassDoc/sassdoc.github.io#81
> Do not try to safe-wipe when unknown or unclear `src`

- src/cli.js
The Node API allows to pass an array of sources. There's no reason the CLI is not allowing to pass multiple sources too.
* Documentation PR: SassDoc/sassdoc.github.io#89
> Allow to pass multiple sources

- package.json
- src/annotation/annotations/alias.js
- src/annotation/annotations/require.js
- src/annotation/annotations/see.js
- src/logger.js
- src/sassdoc.js
- src/utils.js
So `[18:26:48]` instead of superfluous `[2015-01-22 18:26:48]` 
Thoughts ?
> Remove date from logger

- src/sassdoc.js
Example:
```
» Folder "bin" successfully parsed.
» [WARNING] SassDoc could not find anything to document.
* Are you still using `/**` comments? They're no more supported since 2.0.
See <http://sassdoc.com/upgrading/#c-style-comments>.
* Are you documenting actual Sass items (variables, functions, mixins, placeholders)?
SassDoc doesn't support documenting CSS selectors.
See <http://sassdoc.com/frequently-asked-questions/#does-sassdoc-support-css-classes-and-ids->.
» Folder "sassdoc" successfully refreshed.
» Theme "default" successfully rendered.
» Process over. Everything okay!
✓ SassDoc completed after 79ms
```
The current link to `upgrading/#c-style-comments` is broken, but I assume here the development version of the website will be deployed in production.
> Add a helpful warning message when nothing could be documented

- src/annotation/annotations/alias.js
- src/annotation/annotations/require.js
- src/annotation/annotations/see.js
- src/environment.js
- src/logger.js
- src/sassdoc.js
Since an upgrade of JSHint, it does not complain anymore about escaped backticks inside backtick strings.
> Use backticks instead of double quotes in messages

- Makefile
- src/cli.js
* See https://github.com/SassDoc/sassdoc/pull/349#issuecomment-72183157
> Use `-` for `stdin`

- src/parser.js
- src/sassdoc.js
* See #352
It's useful to have a deterministic output, for example I needed this to [compare different branchs of the theme](https://github.com/SassDoc/sassdoc-theme-default/pull/58#issuecomment-72356748).
The `sorter` export is not needed anymore since the parsed data will always be sorted (and again, that's nice for *determinism*). Though I can't remove this export because it would break the API.
I don't believe it's a problem since it won't cause any problem if someone's using the parser/sorter "by and" and the data end up sorted twice.
And the fact the data don't comes out from the parser in a random order anymore is not breaking, since the interface stays the same.
> Sort data directly from the parser

- src/annotation/annotations/index.js
- src/annotation/annotations/name.js
- test/annotations/name.test.js
- test/data/expected.json
- test/data/test.scss
> [RFR] Add @​name annotation

- DEVELOPMENT.md
* Remove potentially dangerous one-liners.
* Describe feature branches and hotfixes.
* Assume the reader is might be forking SassDoc.
* Remove hard reset and force push on `master` when publishing. New feature and hotfixes instructions should prevent this.
> Improve development instructions

- package.json
- src/cli.js
- src/environment.js
- src/sassdoc.js
This needs to be merged with `--no-ff` in both `master` and `develop` after review. Then `make publish` on master.
> [RFR] Graceful relative paths in CLI and config file

- package.json
- src/annotation/annotations/access.js
- test/annotations/access.test.js
* Fix #384
---
Should be merged in both `master` and `develop` once reviewed.
Tested on `sassdoc-theme-default` on my side, works as expected for the following cases:
Case | Behavior
--- | ---
explicit private without underscore | private
explicit public and underscore | public
underscore | private
nothing | public
> Do not try to autofill explicit access

- src/environment.js
> Ensure `default` theme name is properly logged

- package.json
- src/annotation/annotations/example.js
- test/annotations/example.test.js
Fixes SassDoc/sassdoc-theme-default#76
> Strip `@example` indent

- CHANGELOG.md
- src/sassdoc.js
Closes #406.
Documentation PR: SassDoc/sassdoc.github.io#119
> Add a `debug` option

- src/sassdoc.js
The input is not always a folder, it can be a file or a glob pattern too, so the message must be generic enough.
Closes #407.
> Reword parse success message

- .eslintrc
- package.json
- src/annotation/annotations/index.js
- src/annotation/annotations/name.js
- src/annotation/annotations/require.js
- src/annotation/annotations/see.js
- src/sassdoc.js
- test/annotations/envMock.js
- test/annotations/parameter.test.js
- test/annotations/property.test.js
- test/annotations/return.test.js
- test/api/recurse.test.js
- test/env/environment.test.js
- test/mock.js
I just update to latest version of eslint and babel-eslint as these versions are working great in combination with SublimeLinter-contrib-eslint and sublime-babel for SublimeText 3 
We had the rule "comma-dangle" set to "always-multiline" which isn't valid in the latest version of eslint I took the liberty to correct this and fix all undetected cases.
> Update to latest version of eslint and babel-eslint 

- .travis.yml
Travis has a new build infrastructure based on docker which is a lot faster we don't need sudo access so this is an easy fix.
More infos here: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade
> Update to use new infrastructure

- GUIDELINES.md
Currently, the link to JSDoc in the Guidelines documentation is missing a hyperlink.
This branch adds the missing link to http://usejsdoc.org/.
> Fix link to JSDoc in Guidelines

- package.json
- src/annotation/annotations/access.js
- src/annotation/annotations/author.js
- test/data/expected.json
As discussed in #387 I added the flag `overwritePoster` to indicate that an annotation is able to overwrite the poster comment and added it for the discussed annotations. The default behaviour of `multiple` is now to merge both arrays.
> Add overwritePoster flag to annotations

- test/data/expected.json
- test/data/test.scss
This PR adds a test that fails with the version of scss-comment-parser that fails to add line context for CSS blocks, and fails with the older scss-comment-parser that doesn't understand CSS blocks at all, but passes with https://github.com/SassDoc/scss-comment-parser/pull/23
This PR should be expected to fail CI for now. Once https://github.com/SassDoc/scss-comment-parser/pull/23 is merged and a new version of scss-comment-parser is released, I will update this PR to also include an update to the newly-released scss-comment-parser, and then it will pass CI.
> Add CSS block in functional test.

- src/environment.js
- src/sassdoc.js
See #488 
I tried to only scope that warning, so that we don't drastically change all the other behaviours (annotation warnings etc.).
Also removed the CSS selector sentence from the warning since this is no longer true, although we don't do much promotion around it.
> Scope empty data warning under the verbose flag

- src/cli.js
- src/environment.js
- test/env/environment.test.js
Fixes #490 
Following of #489 
The same issue could be trigerred with passing `strict` as well. This MR fixes both.
> Fix verbose flag and environment keys safeguard

- src/parser.js
- test/api/parser.test.js
This adds an option so that a theme can request to see all comments including the ones that are normally filtered out due to not being attached to a Sass block (see #477)
> Add option to avoid filtering empty comments

- src/annotation/annotations/group.js
- src/annotation/annotations/groupDescription.js
- src/annotation/annotations/index.js
- test/annotations/api.test.js
- test/annotations/group.test.js
- test/data/expected.json
- test/data/test.scss
Fixes #520 
@pascalduez had proposed to use an object for `group` instead of adding the `groupDescriptions` key. However, I found that to many places rely on the fact that `group` is a string, so I think this is less invasive.
> Parse group description

- package.json
- yarn.lock
This update was made because this newer version of `vinyl-fs` does not have a dependency on a version of "braces" that is vulnerable to a ReDoS attack. This addresses this issue: https://github.com/SassDoc/sassdoc/issues/537
`vinyl-fs` is used in just a few places in this project and its methods that are used have not changed between version **2.4.4** (the previous version of this dependency that was specified in `package.json` and version **3.0.3**.
Details about the `braces` vulnerability can be found here: https://snyk.io/vuln/npm:braces:20180219
> Update vinyl-fs depedency to version ^3.0.3
